name: Release

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: git-sync
          uses: wei/git-sync@v3
          with:
            source_repo: "mboxplus/mbox-wiki"
            source_branch: "master"
            destination_repo: "mboxplus/mbox.wiki"
            destination_branch: "master"
            source_ssh_private_key: ${{ secrets.GITHUB_TOKEN }}
            destination_ssh_private_key: ${{ secrets.ACCESS_TOKEN }}