name: Release

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Setup Git Access
          run: |
            git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
            git config --global user.email "mbox.runner@mbox.com"
            git config --global user.name "MBox Runner"
        - name: Sync Repo
          run: |
            git remote add target https://github.com/MBoxPlus/mbox.wiki.git
            git push -f --all target main:master
            git push -f --tags target main:master
