name: Release

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Git Access
          run: |
            git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
            git config --global user.email "mbox.runner@mbox.com"
            git config --global user.name "MBox Runner"
        - name: git-sync
          uses: wei/git-sync@v3
          with:
            source_repo: "https://RyanLeeLY:${{ secrets.ACCESS_TOKEN }}@github.com/mboxplus/mbox-wiki.git"
            source_branch: "main"
            destination_repo: "https://RyanLeeLY:${{ secrets.ACCESS_TOKEN }}@github.com/mboxplus/mbox.wiki.git"
            destination_branch: "master"