name: Release

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: wangchucheng/git-repo-sync@v0.1.0
          with:
            target-url: 'https://github.com/mboxplus/mbox.wiki.git'
            target-username: 'MBox Runner'
            target-token: ${{ secrets.ACCESS_TOKEN }}